// port2024-vue/src/components/Skip.vue
<template>
    <div id="skip">
        <a href="#header">헤더 영역 바로가기</a>
        <a href="#intro">인트로 영역 바로가기</a>
        <a href="#skill">스킬 영역 바로가기</a>
        <a href="#site">사이트 영역 바로가기</a>
        <a href="#port">포트 영역 바로가기</a>
        <a href="#contact">컨텍트 영역 바로가기</a>
        <a href="#footer">푸터 영역 바로가기</a>
    </div>
</template>

// port2024-next/src/components/Skip.jsx
import React from 'react'

const Skip = () => {
    return (
        <div id="skip">
            <a href="#header">헤더 영역 바로가기</a>
            <a href="#intro">인트로 영역 바로가기</a>
            <a href="#skill">스킬 영역 바로가기</a>
            <a href="#site">사이트 영역 바로가기</a>
            <a href="#port">포트 영역 바로가기</a>
            <a href="#contact">컨텍트 영역 바로가기</a>
            <a href="#footer">푸터 영역 바로가기</a>
        </div>
    )
}

export default Skip
