// port2024-vue/src/components/Header.vue
<script setup>
import { headerNav } from '../constants/index'
</script>

<template>
    <header id="header" role="banner">
        <div class="header_inner">
            <div class="header_logo">
                <h1>
                    <a href="#">SH<em>VUE.js</em></a>
                </h1>
            </div>
            <nav
                class="header_nav"
                :class="{show: isNavVisible}"
                role="navigation"
                aria-label="메인메뉴"
            >
                <ul>
                    <li v-for="(nav, key) in headerNav" :key="key">
                        <a href="#intro">{{ nav.title }}</a>
                    </li>
                </ul>
            </nav>
            <div
                class="header_nav_mobile"
                id="headerToggle"
                aria-controls="primary-menu"
                :aria-expanded="isNavVisible.toString()"
                role="button"
                tabindex="0"
                @click="toggleMobileMenu"
            >
            <span></span>
        </div>
        </div>
    </header>
</template>

<script>
export default {
    data(){
        return {
            isNavVisible: false
        }
    },
    methods: {
        toggleMobileMenu(){
            this.isNavVisible = !this.isNavVisible;
        }
    }
}
</script>

<style lang="scss" scoped>
@import "@/assets/scss/mixin";

#header {
    @include position-fixed;
    z-index: 10000;
}

.header_inner {
    @include flex-between;
    background-color: rgba(116, 99, 99, 0.1);
    backdrop-filter: blur(15px);
    padding: 1rem;

    .header_logo {
        font-size: 0.9rem;
        text-align: center;
        text-transform: uppercase;
        line-height: 1;

        em {
            font-size: 10px;
            display: block;
            color: var(--black200);
        }
    }

    .header_nav {

        @media (max-width: 800px) {
            display: none;

            &.show {
                display: block;

                ul {
                    display: block;
                    position: absolute;
                    right: 0;
                    top: 68px;
                    background-color: rgba(116,99,99,0.1);
                    backdrop-filter: blur(15px);
                    z-index: 10000;
                    min-width: 150px;
                    padding: 20px 0;

                    li {
                        display: block;
                        text-align: right;

                        a {
                            display: inline-block;
                            padding: 10px;
                        }
                    }
                }
            }

            &.show + .header_nav_mobile span::before {
                width: 20px;
            }

            &.show + .header_nav_mobile span::after {
                width: 20px;
            }
        }

        li{
            display: inline;
    
            a {
                text-transform: uppercase;
                font-size: 14px;
                padding: 14px;
                position: relative;
    
                &::before {
                    content: '';
                    width: calc(100% - 28px);
                    height: 1px;
                    background-color: var(--black);
                    position: absolute;
                    left: 14px;
                    bottom: 10px;
                    transform: scaleX(0);
                    transition: all 0.3s
                }
    
                &:hover::before {
                    transform: scaleX(1);
                }
            }
        }
    }



    .header_nav_mobile {
        display: none;
        width: 40px;
        height: 40px;
        cursor: pointer;

        @media (max-width: 800px) {
            display: block;
        }

        span {
            display: block;
            width: 40px;
            height: 2px;
            background-color: var(--black);
            margin-top: 19px;
            position: relative;

            &::before {
                content: '';
                width: 40px;
                height: 2px;
                background-color: var(--black);
                position: absolute;
                right: 0;
                top: 6px;
                transition: width 0.3s;
            }

            &::after {
                content: '';
                width: 40px;
                height: 2px;
                background-color: var(--black);
                position: absolute;
                left: 0;
                bottom: 6px;
                transition: width 0.3s;
            }
        }
    }
}
</style>

// port2024-react/src/components/Header.jsx
import React, { useState } from "react"
import { headerNav } from "../constants";


const Header = () => {
  const [show, setShow] = useState(false);

  const toggleMenu = () => {
    setShow((prevShow) => !prevShow);
  }

  return (
    <header id="header" role="banner">
        <div className="header_inner">
            <div className="header_logo">
                <h1>
                    <a href="/">SH<em>react.js</em></a>
                </h1>
            </div>
            <nav
              className={`header_nav ${show ? "show" : ""}`}
              role="navigation" aria-label="메인메뉴"
            >
                <ul>
                  {headerNav.map((nav, key) => (
                      <li key={key}>
                        <a href={nav.url}>{nav.title}</a>
                      </li>
                  ))}
                </ul>
            </nav>
            <div
                className="header_nav_mobile"
                id="headerToggle"
                aria-controls="primary-menu"
                aria-expanded={show ? "true" : "false"}
                role="button"
                tabIndex="0"
                onClick={toggleMenu}
            >
            <span></span>
        </div>
        </div>
    </header>
  )
}

export default Header
