// port2024-react/src/components/Intro.jsx
import React from 'react';
import about from '../assets/img/tiger.jpg';
import { introText } from '../constants';

const Intro = () => {
  return (
    <section id="intro">
        <div className="intro_inner">
            <h2 className="intro_title">
                {introText.title}
            </h2>
            <div className="intro_lines" aria-hidden="true">
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
            </div>
            <div className="intro_text">
                <div className="text">
                    <div>{introText.desc[0]}</div>
                    <div>{introText.desc[1]}</div>
                    <div>{introText.desc[2]}</div>
                </div>
                <div className="img">
                    <img src={about} alt="my img" />
                </div>
            </div>
            <div className="intro_lines bottom" aria-hidden="true">
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
                <span className="line"></span>
            </div>
        </div>
    </section>
  )
}

export default Intro

// port2024-vue/src/components/Intro.vue
<script setup>
import { introText } from '../constants/index'
</script>

<template>
    <section id="intro">
        <div class="intro_inner">
            <h2 class="intro_title">
                {{ introText.title }}
            </h2>
            <div class="intro_lines" aria-hidden="true">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
            </div>
            <div class="intro_text">
                <div class="text">
                    <div>{{ introText.desc[0] }}</div>
                    <div>{{ introText.desc[1] }}</div>
                    <div>{{ introText.desc[2] }}</div>
                </div>
                <div class="img">
                    <img src="@/assets/img/tiger.jpg" alt="my img">
                </div>
            </div>
            <div class="intro_lines bottom" aria-hidden="true">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
            </div>
        </div>
    </section>
</template>

<style lang="scss">
#intro {
    height: 100vh;
}

.intro_inner {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: flex-start;
    justify-content: flex-end;
    flex-direction: column;
    padding: 16px;

    .intro_title {
        font-size: 8vw;
        text-transform: uppercase;
        line-height: 1;
        font-weight: 800;
        white-space: nowrap;
        text-indent: -0.5vw;
        letter-spacing: -0.3vw;

        @media (max-width: 480px) {
            display: none;
        }
    }

    @media (max-width: 800px) {
        justify-content: center;
        align-items: center;
    }

    .intro_text {
        width: 100%;
        height: 40vh;
        background-color: var(--black);
        color: var(--white);
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        position: relative;

        .text {
            font-size: 2vw;
            line-height: 1;
            font-weight: 700;
            text-transform: uppercase;
            text-decoration: underline; 
            text-align: center;
            position: relative;
            z-index: 100;
            transition: all 0.3s;
            cursor: all-scroll;
            animation: textAni 1s forwards;

            @media (max-width: 800px) {
                font-size: 24px;
            }

            @keyframes textAni {
                0% {
                    letter-spacing: 20px;
                }
            
                100% {
                    letter-spacing: -2px;
                }
            }

            div:nth-child(2) {
                margin: 10px 0;
            }
        }

        .img {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            width: 30vh;
            height: 30vh;
            border-radius: 50%;
            overflow: hidden;
            filter: grayscale(100%);
            transition: all 0.3s;
        }

        &:hover .text {
            opacity: 0;
        }

        &:hover .img {
            filter: grayscale(0);
        }
    }

    .intro_lines {
        width: 100%;

        .line {
            display: block;
            width: 100%;
            height: 1px;
            background-color: var(--black);
            margin-bottom: 0.5vw;

            &:nth-child(1) {
                height: 1px;
            }
            
            &:nth-child(2) {
                height: 2px;
            }

            &:nth-child(3) {
                height: 5px;
            }

            &:nth-child(4) {
                height: 9px;
            }

            &:nth-child(5) {
                height: 13px;
            }

            &:nth-child(6) {
                height: 17px;
            }

            &:nth-child(7) {
                height: 25px;
            }
        }

        &.bottom {
            .line {
                margin-top: 0.5vw;
                margin-bottom: 0;
                display: none;

                @media (max-width: 800px) {
                    display: block;
                }

                &:nth-child(1) {
                    height: 25px;
                }
                
                &:nth-child(2) {
                    height: 17px;
                }
                
                &:nth-child(3) {
                    height: 13px;
                }
                
                &:nth-child(4) {
                    height: 9px;
                }
                
                &:nth-child(5) {
                    height: 5px;
                }
                
                &:nth-child(6) {
                    height: 2px;
                }
                
                &:nth-child(7) {
                    height: 1px;
                }
            }
        }
    }
}
</style>
