// port2024-vue/src/views/HomeView.vue
<script setup>
import Skip from '@/components/Skip.vue'
import Header from '@/components/Header.vue'
import Intro from '@/components/Intro.vue'
import Skill from '@/components/Skill.vue'
import Site from '@/components/Site.vue'
import Port from '@/components/Port.vue'
import Contact from '@/components/Contact.vue'
import Footer from '@/components/Footer.vue'
</script>

<template>
  <Skip />
  <Header />
  <main id="main" role="main">
    <Intro />
    <Skill />
    <Site />
    <Port />
  </main>
  <Contact />
</template>

// port2024-react/src/views/HomeView.jsx
import React from 'react'
import Header from '../components/Header'
import Skip from '../components/Skip'
import Intro from '../components/Intro'
import Skill from '../components/Skill'
import Site from '../components/Site'
import Port from '../components/Port'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Main from '../components/Main'

const HomeView = () => {
  return (
    <>
        <Skip />
        <Header />
        <Main>
            <Intro />
            <Skill />
            <Site />
            <Port />
            <Contact />
        </Main>
        <Footer />
    </>
  )
}

export default HomeView
